spring:
  mongodb:
    embedded:
      version: 3.5.5
  data:
    mongodb:
      port: 2717
      database: mongoDB
      host: localhost
mongock:
  runner-type: InitializingBean
  change-logs-scan-package: ru.otus.springwork11.data.Changelog