management:
  endpoints:
    web:
      base-path: "/monitor"
      exposure:
        include: "metrics,health,flyway,info"
    enabled-by-default: false

  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
    flyway:
      enabled: true
    info:
      enabled: true

  #Для отражения информации блока
  info:
    env:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  flyway:
    locations: db/migration

  jpa:
    hibernate:
      ddl-auto: none

info:
  app:
    version: @project.version@
    author: aao
    description: application with metrics