management:
  endpoints:
    web:
      base-path: "/monitor"
      exposure:
        include: "metrics,health,logfile,flyway,info"
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
    logfile:
      enabled: true
    flyway:
      enabled: true
    info:
      enabled: true

  #Для отражения информации блока
  info:
    env:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:h2db
  flyway:
    locations: db/migration
  jpa:
    hibernate:
      ddl-auto: none


info:
 app:
   version: @project.version@
   author: aao
   description: application with metrics

#Включить метрики, healthchecks и logfile
logging:
  file:
    name: 1.log