spring:
  datasource:
    url: jdbc:h2:mem:h2db
  flyway:
    enabled: true
    locations: db/migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false

  main:
    allow-circular-references: true