POST https://cleaner.dadata.ru/api/v1/clean/address
//Accept: application/json
Authorization: Token 6bf4017fcff90bb3cd4c10a91b3186876e282bee
Content-Type: application/json
X-Secret: fff66a900b3371a82c9c75715417506ab75c7316

["Красная 10"]